name: Deploy Cloud IAC

on:
  push:
    branches:
    - 'cloud'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Terraform Iniciar
      run: terraform init

    - name: Format Terraform
      run: terraform fmt

    - name: Terraform apply
      run: terraform apply -auto-approve